### DISCUSSION TITLE
Use Nuitka to pack flet desktop app

### DISCUSSION THREAD

**Discussion by ningzichun** [flet-dev/flet#1314] [Show and tell]
I have successfully used Nuitka to pack flet desktop app (tested on flet-0.5.2, Nuitka-1.5.6 and Python-3.11). I think it is absolutely faster than the pyinstaller on MacOS cause it is onedir mode. And I found pyinstaller might have trouble collecting some libraries on Linux, so I looked back and try Nuitka again, seeking for better speed and compatibility.

## Minimal Testcase
Here is the minimal command I used to test the [code](https://github.com/flet-dev/flet/issues/202#issuecomment-1219636428):

### MacOS:
```
python3 -m nuitka --standalone --macos-create-app-bundle --macos-app-mode="ui-element" --include-package-data=flet main.py
```

### Linux:
```
python3 -m nuitka --standalone  --assume-yes-for-downloads --include-package-data=flet --onefile main.py
```

### Windows:
A bit tricky because Nuitka will ignore the *.dll, *.so in the module data directory when using `--include-package-data`, so to avoid downloading flet.exe on startup and to include needed dlls and app.so, we will create a [Nuitka Package Configurarion](https://nuitka.net/doc/nuitka-package-config.html) such as `scripts/nuitka_flet.yml` with:
```
- module-name: 'flet'
  data-files:
     dirs:
       - 'bin'
  dlls:
    - from_filenames:
        relative_path: 'bin/flet'
        prefixes:
          - '*'
        suffixes:
          - 'dll'
        dest_path: 'flet/bin/flet'
    - from_filenames:
        relative_path: 'bin/flet/data'
        prefixes:
          - '*'
        suffixes:
          - 'so'
        dest_path: 'flet/bin/flet/data'
      
```
Then we run the command to compile:
```
python -m nuitka --standalone  --assume-yes-for-downloads --onefile  --user-package-configuration-file=scripts/nuitka_flet.yml main.py
```

## For Production
Also, I would like to share the full command I used to build my project in the buildbot:

### MacOS:
```
python3 -m nuitka --standalone --macos-create-app-bundle --macos-app-icon=scripts/icon.png --output-dir=dist --follow-imports --assume-yes-for-downloads --include-data-dir=resources=resources  "Desktop.py"  --macos-app-mode="ui-element" --macos-signed-app-name="com.example.desktop" --include-package-data=flet --nofollow-import-to=torch 
cd dist/
tar -cvf "app.tar" "Desktop.app"/
```
### Linux:
```
python3 -m nuitka --standalone  --linux-icon=scripts/icon.png --output-dir=dist --include-data-dir=resources=resources  --nofollow-import-to=torch --assume-yes-for-downloads --include-package-data=flet --onefile "Desktop.py"
mv dist/Desktop.bin dist/Desktop
```
### Windows:
```
python -m nuitka --standalone --disable-console --windows-icon-from-ico=scripts/icon.png --assume-yes-for-downloads --output-dir=dist --follow-imports --nofollow-import-to=torch --onefile --include-data-dir=resources=resources --file-description="Desktop Client" --copyright="copyright" --product-version="1.0" --user-package-configuration-file=scripts/nuitka_flet.yml "Desktop.py"
```

To be updated with more tests, like trimming the included data...
