### DISCUSSION TITLE
Flet is installing `fastapi[all]` but flet should only install `fastapi`

### DISCUSSION THREAD

**Discussion by baseplate-admin** [flet-dev/flet#4478] [General]
**Description**

I installed flet `0.22.1` today and saw it installed `fastapi[all]` by default. This should not be the case

**Code example to reproduce the issue:**

![image](https://github.com/flet-dev/flet/assets/61817579/aad50217-a2a1-4648-b07a-70792c2ebf85)

**Describe the results you received:**

```
email_validator = ">=2.0.0"
fastapi-cli = ">=0.0.2"
httpx = ">=0.23.0"
jinja2 = ">=2.11.2"
orjson = ">=3.2.1"
pydantic = ">=1.7.4,<1.8 || >1.8,<1.8.1 || >1.8.1,<2.0.0 || >2.0.0,<2.0.1 || >2.0.1,<2.1.0 || >2.1.0,<3.0.0"
python-multipart = ">=0.0.7"
starlette = ">=0.37.2,<0.38.0"
typing-extensions = ">=4.8.0"
ujson = ">=4.0.1,<4.0.2 || >4.0.2,<4.1.0 || >4.1.0,<4.2.0 || >4.2.0,<4.3.0 || >4.3.0,<5.0.0 || >5.0.0,<5.1.0 || >5.1.0"
```

these were installed.

**Describe the results you expected:**

Those extensions should not have been installed

**Additional information you deem important (e.g. issue happens only occasionally):**

**Flet version (`pip show flet`)**:

```
Name: flet
Version: 0.22.1
Summary: Flet for Python - easily build interactive multi-platform apps in Python
Home-page:
Author: Appveyor Systems Inc.
Author-email: hello@flet.dev
License: Apache-2.0
Location: C:\Users\zarif\AppData\Local\pypoetry\Cache\virtualenvs\coreproject-CGb-jJ-B-py3.12\Lib\site-packages
Requires: cookiecutter, fastapi, flet-runtime, packaging, qrcode, uvicorn, watchdog
Required-by:
```

**Give your `requirements.txt` file (don't `pip freeze`, instead give direct packages):**

```toml
[tool.poetry]
name = "test-flet"
version = "0.1.0"
description = ""
authors = ["baseplate-admin <61817579+baseplate-admin@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
flet = "^0.22.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

```

**Operating system**:

Windows/11

**Additional environment details:**
Poetry
