### DISCUSSION TITLE
Enabling storage permissions in pyproject.toml doesn't work, when building the apk I find it in androidmanifest but i still have access denied

### DISCUSSION THREAD

**Discussion by Faiz12002** [flet-dev/flet#4953] [General]
Hello, so I tried to test different permissions on flet, and I took the code from the documentation, permissions like microphone works, but for storage it doesn't work, when i press the button to request storage permission it says permission denied

here's the python code

```python
import flet as ft


def main(page: ft.Page):
    page.scroll = ft.ScrollMode.ADAPTIVE
    page.appbar = ft.AppBar(title=ft.Text("PermissionHandler Tests"))
    ph = ft.PermissionHandler()
    page.overlay.append(ph)

    def check_permission(e):
        o = ph.check_permission(e.control.data)
        page.add(ft.Text(f"Checked {e.control.data.name}: {o}"))

    def request_permission(e):
        o = ph.request_permission(e.control.data)
        page.add(ft.Text(f"Requested {e.control.data.name}: {o}"))

    def open_app_settings(e):
        o = ph.open_app_settings()
        page.add(ft.Text(f"App Settings: {o}"))

    page.add(
        ft.OutlinedButton(
            "Check Microphone Permission",
            data=ft.PermissionType.STORAGE,
            on_click=check_permission,
        ),
        ft.OutlinedButton(
            "Request Microphone Permission",
            data=ft.PermissionType.STORAGE,
            on_click=request_permission,
        ),
        ft.OutlinedButton(
            "Open App Settings",
            on_click=open_app_settings,
        ),
    )

ft.app(main)
```
and here's the part in pyproject.toml for adding various permissions

```toml
[tool.flet.android.permission]

# Camera access
"android.permission.CAMERA" = true

# Read and write external storage (for storing files in /storage/emulated/0/)
"android.permission.READ_EXTERNAL_STORAGE" = true
"android.permission.WRITE_EXTERNAL_STORAGE" = true

# Manage external storage (Android 11+ for full access)
"android.permission.MANAGE_EXTERNAL_STORAGE" = true

# Internet access (useful for API calls, web views, etc.)
"android.permission.INTERNET" = true

# Location services
"android.permission.ACCESS_FINE_LOCATION" = true
"android.permission.ACCESS_COARSE_LOCATION" = true

# Microphone access (for recording audio)
"android.permission.RECORD_AUDIO" = true

# Phone state access (for reading device status)
"android.permission.READ_PHONE_STATE" = true

# Vibration control
"android.permission.VIBRATE" = true

# Bluetooth access
"android.permission.BLUETOOTH" = true
"android.permission.BLUETOOTH_ADMIN" = true

# NFC access (for near-field communication)
"android.permission.NFC" = true
```
