### DISCUSSION TITLE
Minimum configuration for deploying to google app engine

### DISCUSSION THREAD

**Discussion by nascin** [flet-dev/flet#512] [Ideas]
I would like a small tutorial to deploy an app on the google cloud platform. I would like to deploy my app in a more professional environment.

**Comment by FeodorFitsner** [comment]
I have experience with that.

In general, you have to deploy to App Engine "flexible" environment with "custom" runtime.
A new GCP "project" must be created for GAE app. One app - one project.

Your main deployment objective is to build a container with your Flet app (I think [this Dockerfile](https://github.com/flet-dev/examples/blob/main/python/apps/icons-browser/Dockerfile) would be a good base and it's slim enough).

Push container to Google Container Registry (GCR) in your project's region.

Describe GAE app with `app.yaml`. This is a good example for Pglet (Flet predecessor): https://github.com/pglet/gae/blob/main/app.yaml

Deploy the app from a GCR container from UI or Google SDK CLI: https://github.com/pglet/gae#readme

You may check GAE docs for mapping custom domain, enabling SSL, etc.

Give it a try - it should be pretty smooth.

Waiting for PR to Flet docs with your experience :)

**Reply by nascin** [reply]
I can't open the given pglet links.

**Comment by FeodorFitsner** [comment]
Fair enough - that's repo is apparently private. Sorry about that!

Here you go: https://gist.github.com/FeodorFitsner/3afbb07753a19f13bc3e2fbbc1a4637e

**Comment by nascin** [comment]
I don't have any experience with google cloud, but with the minimal configuration you provided, I was able to successfully deploy.

The files looked like this:

**File:** `app.yaml`
```
runtime: custom
env: flex

manual_scaling:
  instances: 1

resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 10

network:
  name: default

env_variables:
  GIN_MODE: release
  # Enable Google Secret Manager
  GOOGLE_SECRET_MANAGER_PROJECT: nascin-wallet
```

**File:** `Dockerfile`
```
FROM python:3-alpine

WORKDIR /app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8080

CMD ["python", "./main.py"]
```
