### ISSUE TITLE
`pyproject.toml` for Flet project metadata, running and building settings

### ISSUE THREAD

**Issue by FeodorFitsner** [flet-dev/flet#3345]
`flet run` CLI commands have a lot of options right now, especially `flet build`.

New controls/packages require even more settings, options, variables, etc.

We are going to use [`pyproject.toml`](https://packaging.python.org/en/latest/specifications/pyproject-toml/) with `tool.flet.*` tables for Flet-specific stuff.

`pyproject.toml` will be created with `flet create` command as part of the new project.

A new `flet init` command will be added to generate `pyproject.toml` file.

Flet's `pyproject.toml` reference (we are going to list only settings required for Flet CLI):

```toml
[project]
name = "my-app" # --project
version = "1.0.0" # --build-version
description = "A brief description to use for executable or bundle" # --description
license = "MIT"
dependencies = [
  "flet",
  "numpy"
]

[tool.flet.template]

path = "gh:some-github/repo" # --template
dir = "" # --template-dir
ref = "" # --template-ref

[tool.flet]
build_number = 1
build_arch = "x86_64" # works for macOS builds only. Build universal package if no arch provided.
org = "my.company" # --org
product = "Project display name" # --product
company = "My Company" # --company
copyright = "Copyright (c) 2024 by Company" # --copyright

app.module = "main" # --module-name
app.path = "src" # python_app_path
app.exclude = ["assets"] #--exclude

splash.color = "" # --splash-color
splash.dark_color = "" # --splash-dark-color
splash.web = false # --no-web-splash
splash.ios = false # --no-ios-splash
splash.android = false # --no-android-splash

compile.app = false # --compile-app
compile.packages = false # --compile-packages
compile.cleanup = false # --cleanup-on-compile

permissions = ["camera", "microphone"] # --permissions

flutter.build_args = [""] # --flutter-build-args
flutter.dependencies = ["flet_video", "flet_audio"] # --include-packages

#[tool.flet.flutter.dependencies]
#flet_video = "1.0.0"
#flet_audio = "2.0.0"

deep_linking.scheme = "https" # --deep-linking-url
deep_linking.host = "mydomain.com" # --deep-linking-url

[tool.flet.flutter.pubspec]

dependency_overrides = []

[tool.flet.ios]

team = "team_id" # --team

deep_linking.scheme = "https" # --deep-linking-url
deep_linking.host = "mydomain.com" # --deep-linking-url

[tool.flet.ios.info] # --info-plist

NSCameraUsageDescription = "This app uses the camera to ..."

[tool.flet.android]

adaptive_icon_background = "" # --android-adaptive-icon-background
split_per_abi = false # --split-per-abi

permission."android.permission.CAMERA" = true # --android-permissions
permission."android.permission.CAMERA" = true

deep_linking.scheme = "https" # --deep-linking-url
deep_linking.host = "mydomain.com" # --deep-linking-url

# store and key passwords can be passed with `--android-signing-key-store-password`
# and `--android-signing-key-password` options or
# FLET_ANDROID_SIGNING_KEY_STORE_PASSWORD
# and FLET_ANDROID_SIGNING_KEY_PASSWORD environment variables.
signing.key_store = "path/to/store.jks" # --android-signing-key-store
signing.key_alias = "upload"

[tool.flet.android.feature]

"android.hardware.camera" = false # --android-features

[tool.flet.macos]

entitlement."com.apple.security.personal-information.photos-library" = true

[tool.flet.web]

base_url = "/" # --base-url
renderer = "canvaskit" # --web-renderer
use_color_emoji = false # --use-color-emoji
route_url_strategy = "path" # --route-url-strategy

```

Permissions:
* https://pub.dev/packages/permission_handler
* Android: https://github.com/Baseflow/flutter-permission-handler/blob/main/permission_handler/example/android/app/src/main/AndroidManifest.xml
* iOS: https://github.com/Baseflow/flutter-permission-handler/blob/main/permission_handler/example/ios/Runner/Info.plist

Impeller: ON/OFF - [option](https://docs.flutter.dev/perf/impeller#android)

Windows manifest: https://learn.microsoft.com/en-us/windows/win32/hidpi/setting-the-default-dpi-awareness-for-a-process
