### ISSUE TITLE
Enhance pyproject.toml support for mobile Ads

### ISSUE THREAD

**Issue by ndonkoHenri** [flet-dev/flet#4174]
Admob Guide: https://developers.google.com/admob/flutter/quick-start#platform_specific_setup
Needed in #3288

**Comment by FeodorFitsner** [comment]
## Configuring AdMob app ID for Android

Command line:

```
flet build apk ... --android-meta-data com.google.android.gms.ads.APPLICATION_ID=ca-app-pub-xxxxxxxxxxxxxxxx~yyyyyyyyyy
```

`pyproject.toml`:

```toml
[tool.flet.android.meta_data]
"com.google.android.gms.ads.APPLICATION_ID" = "ca-app-pub-xxxxxxxxxxxxxxxx~yyyyyyyyyy"
```

## Configuring AdMob app ID for iOS

Command line:

```
flet build apk ... --info-plist GADApplicationIdentifier=ca-app-pub-xxxxxxxxxxxxxxxx~yyyyyyyyyy
```

`pyproject.toml`:

```toml
[tool.flet.ios.info]
GADApplicationIdentifier = "ca-app-pub-xxxxxxxxxxxxxxxx~yyyyyyyyyy"
```
