### ISSUE TITLE
`flet build` generates APK with a black icon

### ISSUE THREAD

**Issue by FeodorFitsner** [flet-dev/flet#4244]
### Duplicate Check

- [X] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### Describe the bug

Building APK with default settings yields black icon.
Related Flutter issue: https://github.com/fluttercommunity/flutter_launcher_icons/issues/600

### Code sample

<details open><summary>Code</summary>

```python
import flet as ft


def main(page: ft.Page):
    page.add(ft.SafeArea(ft.Text("Hello, Flet!")))


ft.app(main)
```

</details>

### To reproduce

```toml
[tool.poetry]
name = "my_app"
version = "1.0.0"
description = "My first Flet project"
authors = ["Feodor Fitsner"]

[tool.poetry.dependencies]
python = "^3.8"
flet = "0.25.0.dev3526"
```

Run the following command to build APK:

`flet build apk`

### Screenshots / Videos

<details open>
<summary>Captures</summary>

[Upload media here]

</details>

### Operating System

macOS

### Operating system details

Any version

### Flet version

0.25.0

### Regression

I'm not sure / I don't know

### Suggestions

Set `adaptive_icon_background` to any non-black color, for example white:

```toml
[tool.flet]
android.adaptive_icon_background = "#ffffff"

[tool.poetry]
name = "my_app"
version = "1.0.0"
description = "My first Flet project"
authors = ["Feodor Fitsner"]

[tool.poetry.dependencies]
python = "^3.8"
flet = "0.25.0.dev3526"
```

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>
