### ISSUE TITLE
Add platform-specific `dependencies` to `pyproject.toml`

### ISSUE THREAD

**Issue by FeodorFitsner** [flet-dev/flet#4601]
### Duplicate Check

- [X] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### Describe the requested feature

A common for all platforms dependencies can be defined in `pyproject.toml` as:

```toml
[project]
dependencies = [
  "plyer==2.1.0"
]
```

or for Poetry configs:

```toml
[tool.poetry.dependencies]
plyer = "2.1.0"
```

The should be an ability to configure dependencies for each of the supported platforms: `ios`, `android`, `windows`, `macos`, `linux` and `web`, for example:

```toml
[tool.flet.ios]
dependencies = [
  "pyobjus"
]

[tool.flet.android]
dependencies = [
  "pyjnius"
]
```
