### ISSUE TITLE
flet build windows ->ModuleNotFoundError: No module named 'src'

### ISSUE THREAD

**Issue by marc-svg** [flet-dev/flet#4606]
### Duplicate Check

- [X] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### Describe the bug

Hi,
after building myapp with:
flet create myapp
and building it with:
flet build windows   (using the generated toml file, nothing changed):

I get this error:

Traceback (most recent call last):
  File "<string>", line 47, in <module>
  File "<frozen runpy>", line 229, in run_module
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\marce\AppData\Roaming\Flet\myapp\flet\app\main.py", line 3, in <module>
    from src.models.user import User
ModuleNotFoundError: No module named 'src'

In the code generated I juste added in main.py:
print(User(name="User Name")) under def main(page: ft.Page):
with of course the module models/user.py like this:

![image](https://github.com/user-attachments/assets/7249488f-c81b-49f9-9c73-cdfed1d893d9)

```python
import flet as ft

from src.models.user import User


def main(page: ft.Page):
    print(User(name="User Name"))

    counter = ft.Text("0", size=50, data=0)

    def increment_click(e):
        counter.data += 1
        counter.value = str(counter.data)
        counter.update()

    page.floating_action_button = ft.FloatingActionButton(
        icon=ft.Icons.ADD, on_click=increment_click
    )
    page.add(
        ft.SafeArea(
            ft.Container(
                counter,
                alignment=ft.alignment.center,
            ),
            expand=True,
        )
    )


ft.app(main)
```

toml file:

```toml
[project]
name = "myapp"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
  "flet==0.25.2"
]


[tool.flet]
# org name in reverse domain name notation, e.g. "com.mycompany".
# Combined with project.name to build bundle ID for iOS and Android apps
org = "com.mycompany"

# project display name that is used as an app title on Android and iOS home screens,
# shown in window titles and about app dialogs on desktop.
product = "myapp"

# company name to display in about app dialogs
company = "Flet"

# copyright text to display in about app dialogs
copyright = "Copyright (C) 2024 by Flet"

[tool.flet.app]
path = "src"
```

Thanks for help

### Code sample

<details open><summary>Code</summary>

```python
import flet as ft

from src.models.user import User


def main(page: ft.Page):
    print(User(name="User Name"))

    counter = ft.Text("0", size=50, data=0)

    def increment_click(e):
        counter.data += 1
        counter.value = str(counter.data)
        counter.update()

    page.floating_action_button = ft.FloatingActionButton(
        icon=ft.Icons.ADD, on_click=increment_click
    )
    page.add(
        ft.SafeArea(
            ft.Container(
                counter,
                alignment=ft.alignment.center,
            ),
            expand=True,
        )
    )


ft.app(main)
```

models/user.py
```python

from dataclasses import dataclass


@dataclass
class User:
    name: str

```

</details>

### To reproduce

flet build windows

### Screenshots / Videos

<details open>
<summary>Captures</summary>

[Upload media here]

</details>

### Operating System

Windows

### Operating system details

Windows 11

### Flet version

0.25.2

### Regression

I'm not sure / I don't know

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>
