### ISSUE TITLE
Error: "ERR_ACCESS_DENIED" when WebView tries to load local file

### ISSUE THREAD

**Issue by DaikyXendo** [flet-dev/flet#4627]
### Duplicate Check

- [X] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### Describe the bug

My app runs fine when I run "flet run"
However when I build the apk and run it on the emulator, the WebView gives the following error:
```
Webpage not available
The webpage at file:///data/data/com.mycompany.test_app/files/flet/app/index.html could not be loaded because:

net::ERR_ACCESS_DENIED
```

I know using ```os.path.abspath``` is really silly but it's the only way I found to get the app to run "normally" on my computer
Is there a way to fix this?
There's very little documentation on WebView and Assets

### Code sample

<details open><summary>Code</summary>

```python
import flet as ft
import os


def main(page: ft.Page):
    js_path = "file://" + os.path.abspath("src/assets/lib/JsLib.js")

    html_str = f"""
<html>
    <head>
        <script
            type="text/javascript"
            async
            src="{js_path}">
        </script>
    </head>
    ...
</html>
    """

    with open("index.html", "w") as f:
        f.write(html_str)

    web_view = ft.WebView(
        url="file://" + os.path.abspath("index.html"),
        enable_javascript=True,
        expand=True,
    )

    page.add(web_view)

    page.update()


ft.app(main)
```

</details>

### To reproduce

Steps:
1: Build the project with: ```flet build apk --include-packages flet_webview``` (flutter 3.24.5)
2: After creating the apk file, install it on the emulator
3: Wait a few seconds and there will be an error message

### Operating System

macOS

### Operating system details

Macos Ventura 13.7.1

### Flet version

0.25.2

### Regression

No, it isn't

### Suggestions

I just wish there was clearer documentation about WebView when loading html file or html string with related Js files. Thanks!

**Comment by gopalparashar421** [comment]
Hey there! I know it's been sometime since this issue was opened. Can you try to add the following snippet to your `pyproject.toml`?

``` toml
[tool.flet.android.permission]
"android.permission.INTERNET" = true
"android.permission.READ_EXTERNAL_STORAGE" = true
"android.permission.WRITE_EXTERNAL_STORAGE" = true

[tool.flet.android.manifest_application]
usesCleartextTraffic = "true"
requestLegacyExternalStorage = "true"
```
