### ISSUE TITLE
`flet build` issues in 0.26.0-dev

### ISSUE THREAD

**Issue by FeodorFitsner** [flet-dev/flet#4727]
1. Cannot override `assets` section in `pubspec.yaml`. This should work:

```toml
[tool.flet.flutter.pubspec.flutter]
assets = []
```

2. Enable desktop after flutter installation. See `flutter config --help`.
3. Set JDK and Android paths. See `flutter config --help`.
4. `flet-*` packages should have no version constraint for `flet` dependency.
