### ISSUE TITLE
flet-lottie error when try to build app

### ISSUE THREAD

**Issue by osamalzabidi** [flet-dev/flet#4799]
### Duplicate Check

- [x] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### Describe the bug

The python app can't found the `flet_lottie` module after upgrade from `0.25.2` to `0.26.0`

## I get this err
ModuleNotFoundError: No module named 'flet_lottie'`

### Code sample

<details open><summary>Code</summary>

```python
[Paste your code here]
```

</details>

### To reproduce

- run repo actions
- build for apk
- run on android device

### Screenshots / Videos

<details open>
<summary>Captures</summary>

[Upload media here]

</details>

### Operating System

Linux

### Operating system details

latest

### Flet version

0.26.0

### Regression

Yes, it used to work in a previous Flet version (please specify the version in additional details)

### Suggestions

adding the flet_lottie to Python bundle, or packages

### Logs

<details open><summary>Logs</summary>

```console
Traceback (most recent call last):
  File "<string>", line 95, in <module>
  File "<frozen runpy>", line 229, in run_module
  File "<frozen runpy>", line 88, in _run_code
  File "/tmp/serious_python_tempEJTEUJ/main.py", line 5, in <module>
  File "/tmp/serious_python_tempEJTEUJ/lib/app.py", line 6, in <module>
  File "/tmp/serious_python_tempEJTEUJ/lib/constant.py", line 9, in <module>
ModuleNotFoundError: No module named 'flet_lottie'
```

</details>

### Additional details

Prev `flet` version 0.25.2

**Comment by omamkaz** [comment]
> What do you have in app's `pyproject.toml`?

```toml
[tool.poetry]
name = "ynet"
version = "13.0.0"
description = "Yemen Net Internet Services"
authors = ["Osama Mohammed <omamkaz@gmail.com>"]
readme = "README.md"


[tool.flet]
# org name in reverse domain name notation, e.g. "com.mycompany".
# Combined with project.name to build bundle ID for iOS and Android apps
org = "com.omamkaz"

# project display name that is used as an app title on Android and iOS home screens,
# shown in window titles and about app dialogs on desktop.
product = "ynet"

# company name to display in about app dialogs
company = "omamkaz"

# copyright text to display in about app dialogs
copyright = "Copyright (C) 2024 by omamkaz"

build_number = 13

dependencies = [
    "flet-lottie",
    "flet==0.26.0",
    "bs4==0.0.2",
    "requests==2.32.3",
    "humanize==4.10.0",
    "pydal==20241201.2"
]

[tool.flet.flutter]
build_args = ["--release", "--analyze-size", "--target-platform", "android-arm"] # android-arm64
dependencies = ["flet_lottie"]


[tool.flet.compile]
app = true
packages = true
cleanup = true


[tool.flet.android]
split_per_abi = true
build_arch = "armeabi-v7a" # arm64-v8a
adaptive_icon_background = "#003374"


[tool.flet.app]
path = "src"
exclude = ["media", "fastlane", "assets/animations", ".github", ".git"]


[tool.poetry.dependencies]
python = ">=3.10,<4"
flet = "0.26.0"
bs4 = "0.0.2"
requests = "2.32.3"
humanize = "4.10.0"
pydal = "20241201.2"
flet-lottie = "0.1.0"


[tool.poetry.group.dev.dependencies]
flet = {extras = ["all"], version = "0.26.0"}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```
