### ISSUE TITLE
tool.poetry.dependencies does not work with local path for importing local python project source as dependency

### ISSUE THREAD

**Issue by duyanh-y4n** [flet-dev/flet#4833]
### Duplicate Check

- [x] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### Describe the bug

I want to add** myotherproject** to flet project with path dependencies in poetry. However, it seems like it has not been implemented in #4554   
(myotherproject is another python project folder managed by poetry)
Until flet 0.23.2, I use poetry export plugin to generate requirements.txt for building the app and it works fine. With flet version 0.26.0 I can not use the old method anymore since requirements.txt is ignored if pyproject.toml is present. 

### Code sample

<details open><summary>pyproject.toml</summary>

```toml
[tool.poetry.dependencies]
python = ">=3.10,<4.0"
myotherproject = {path = "../myotherproject", develop = false}
xlsxwriter = "^3.2.0"
tzlocal = "^5.2"
flet = "^0.26.0"
```

</details>

### To reproduce

Use poetry export to generate requirements.txt. For example:

```shell
	poetry export -o src/myfletapp/requirements.txt --without-hashes
```

### Expected behavior

**myproject** is added in requirements.txt as:

```txt
myproject @ file:///absolute/path/to/myproject ; python_version >= "3.10" and python_version < "4.0"
...(other dependncies entries)
```
This should work fine when using **flet build** (until flet 0.23.2)

### Screenshots / Videos

<details open>
myotherproject use **httpx**, which requires ***certifi** lib
<summary>built app binary launch</summary>

![Image](https://github.com/user-attachments/assets/2a6b7edf-4336-4b78-a02c-e975b385ac67)

</details>

### Operating System

Linux

### Operating system details

archlinux

### Flet version

0.26.0

### Regression

No, it isn't

### Suggestions

- Implement this feature to add other python project by path dependency as build source 
OR
- add an option to choose requirements.txt or pyproject.toml as build dependencies list

I think the second option is easier to implement and also make `flet build` somehow more flexible for specific use cases. By forcing to use pyproject.toml by default might not be a better choice since it is not used the same way by different tools like poetry, uv, etc.

Thank you in advance!

**Comment by FeodorFitsner** [comment]
You can add an absolute path to your project into `dependencies` section of `pyproject.toml`:

```toml
[project]
dependencies = [
  "myproject @ file:///absolute/path/to/myproject",
  "xlsxwriter>=3.2.0",
  "tzlocal>=5.2",
  "flet>=0.26.0"
]
```

Switch to Poetry 2.0 and you won't need `[tool.poetry.dependencies]` anymore. Poetry 2.0 has full support for `[project]`.

Or you can try adding a full path to Poetry dependencies:

```toml
[tool.poetry.dependencies]
myotherproject = {path = "file:///absolute/path/to/myproject", develop = false}
```
