### ISSUE TITLE
Editable packages in `pyproject.toml` to install  from a path by `flet build` command

### ISSUE THREAD

**Issue by FeodorFitsner** [flet-dev/flet#4963]
Provide the ability to specify "editable" (or "develop") packages in `pyproject.toml` configuration.
Such package is a pair of "name = path" and `flet build` command will be installing the package from a path if its name presents in `dependencies`.

Example configuration:

```toml
[project]
dependencies = [
  "flet==0.27.1",
  "my_awesome_package"
]

[tool.flet.dev_packages]
my_awesome_package = "../.." # relative path
```

`--no-cache-dir` will be added to package command if develop packages exist.
