### ISSUE TITLE
Setting Android manifest `<application>` element properties in `pyproject.toml`

### ISSUE THREAD

**Issue by FeodorFitsner** [flet-dev/flet#4977]
### Discussed in https://github.com/flet-dev/flet/discussions/4968

<div type='discussions-op-text'>

<sup>Originally posted by **JudicaelK** February 24, 2025</sup>
Hi,

How to set requestLegacyExternalStorage to true through pyproject.toml file for flet project?

I tried 

[tool.flet.android]
requestLegacyExternalStorage = true

but it doesn't work.

Any idea?

Thanks.</div>

**Comment by FeodorFitsner** [comment]
The solution is addition of `pyproject` variable to `flet build` template, so you can access any section/setting in pyproject.toml, for example:

`pyproject.toml`:

```toml
[tool.flet.android]
requestLegacyExternalStorage = true
```

In `flet build` template we can access that variable as:

```
{{ cookiecutter.pyproject.tool.flet.android.requestLegacyExternalStorage }}
```

**Comment by FeodorFitsner** [comment]
Final solution: additional properties to `<application>` element of Android manifest can be added as:

```toml
[tool.flet.android.manifest_application]
requestLegacyExternalStorage = "true"
```
